// Auto-generated by tools/gen_font_tga_template.py
// Encoding: ISO-8859-1 (Latin-1) single-byte characters.
// IMPORTANT: The first character must be a space.

#pragma once

// Palette index 1 in the TGA file is used as the background and becomes transparent.
// Jo Engine adds +1 to palette indices, so pass 2 to jo_tga_8bits_loader().
#define SATURN_FONT_TGA_TRANSPARENT_COLOR_INDEX_IN_PALETTE 2

#define SATURN_FONT_MAPPING_STR " !\"#$%&'()*+,-./0123456789:;<=>?@ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz{|}~" "\xAB" "\xB3" "\xC0" "\xC1" "\xC3" "\xC7" "\xC9" "\xCA" "\xD3" "\xD4" "\xDA" "\xE0" "\xE1" "\xE2" "\xE3" "\xE7" "\xE9" "\xEA" "\xED" "\xF2" "\xF3" "\xF4" "\xF5" "\xFA" "\xFC"
